name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint (PHP)
        run: vendor/bin/pint --test

      - name: Check Frontend Files
        run: |
          if [ -d "resources/js" ] && [ -n "$(find resources/js -name '*.vue' -o -name '*.ts' -o -name '*.js' | head -1)" ]; then
            echo "Frontend files found, running frontend linting..."
            npm run format:check || echo "Format check failed, but continuing..."
            npm run lint || echo "Lint failed, but continuing..."
          else
            echo "No frontend files found, skipping frontend linting"
          fi

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
